# Machine Learning - Project 2 (**3/3**)

### Team Members:

Mauro Travieso Pena

Quoc Huy Luong

Ngoc Bao Tran

In [0]:

import pandas as pd
import numpy as np

credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies_img.csv')
credits.columns = ['id','tittle','cast','crew']
nRows=11

#https://www.kaggle.com/ibtesama/getting-started-with-a-movie-recommendation-system
from ast import literal_eval
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan
  
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        #Check if more than 3 elements exist. If yes, return only first three. If no, return entire list.
        if len(names) > 3:
            names = names[:3]
        return names

    #Return empty list in case of missing/malformed data
    return []

def convertTime(minutes): 
    hour = minutes // 60
    minutes = minutes % 60   
    return "%dh%02d" % (hour, minutes) 
  
def paserData(input):
  
  data = input.copy()
  
  features = ['cast', 'crew', 'keywords', 'genres','production_companies']
  for feature in features:
    data[feature] = data[feature].apply(literal_eval)
    
  data['director'] = data['crew'].apply(get_director)

  features = ['cast', 'keywords', 'genres','production_companies','crew']
  for feature in features:
    data[feature] = data[feature].apply(get_list)
    
        
    
  newData = data  
  return newData

def combineData(credits,movies):
  imageURL='https://image.tmdb.org/t/p/original'
  
  data = pd.merge(movies,credits, how='left', on=['id'])
  
  
  data['imgURL'] = imageURL + movies['poster_path']
  data['runtime'] = data['runtime'].fillna(0)
  data['runtime'] = data['runtime'].astype('int')
  data['score'] = data['vote_average']
  data['release_date'] = data['release_date'].fillna('1900-01-01')
  data['year'] = pd.to_datetime(data['release_date']).dt.year
  data['runtime_str'] = data['runtime'].astype('int').apply(convertTime)
  
  data = paserData(data)
  
  return data

In [27]:
newMoviesData= combineData(credits,movies)
newMoviesData.head()

      budget  ...           director
0  237000000  ...      James Cameron
1  300000000  ...     Gore Verbinski
2  245000000  ...         Sam Mendes
3  250000000  ...  Christopher Nolan
4  260000000  ...     Andrew Stanton

[5 rows x 29 columns]

# Demographic Filtering

In [0]:
#https://www.kaggle.com/ibtesama/getting-started-with-a-movie-recommendation-system
def weighted_rating(x, m, C):
    v = x['vote_count']
    R = x['vote_average']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(m+v) * C)

In [0]:
#returnColumns = ['id','title','popularity','overview','runtime','poster_path','score','vote_average','vote_count','genres','cast','crew','production_companies','keywords','year']
returnColumns = ['id','title','imgURL','score','popularity']
def demoGraphicFilteringByRatingScore(data,topN=10):
  C = data['vote_average'].mean()
  m= data['vote_count'].quantile(0.9)
  q_movies = data.copy().loc[data['vote_count'] >= m]
  q_movies['score'] = q_movies.apply(weighted_rating,args=(m,C),axis=1)
  
  q_movies = q_movies.sort_values('score', ascending=False)
  
  
  q_movies = q_movies.head(topN)
  
  q_movies = q_movies[returnColumns]
 
  
  return q_movies

In [0]:
def demoGraphicFilteringByPopularity(data,topN=10):
  q_movies = data.copy()
  q_movies = q_movies.sort_values('popularity', ascending=False)
  
  q_movies = q_movies.head(topN)
  
 
  q_movies = q_movies[returnColumns]
  
  return q_movies

In [31]:
demoGraphicFilteringByRatingScore(newMoviesData,11)

          id  ...  popularity
1883     278  ...  136.747729
662      550  ...  146.757391
65       155  ...  187.322927
3234     680  ...  121.463076
96     27205  ...  167.583710
3339     238  ...  143.659698
95    157336  ...  724.247784
809       13  ...  138.133331
329      122  ...  123.630332
1992    1891  ...   78.517830
262      120  ...  138.049577

[11 rows x 5 columns]

In [32]:
demoGraphicFilteringByPopularity(newMoviesData,11)

         id  ...  popularity
546  211672  ...  875.581305
95   157336  ...  724.247784
788  293660  ...  514.569956
94   118340  ...  481.098624
127   76341  ...  434.278564
28   135397  ...  418.708552
199      22  ...  271.972889
82   119450  ...  243.791743
200  131631  ...  206.227151
88   177572  ...  203.734590
108   87101  ...  202.042635

[11 rows x 5 columns]

# Content Based Filtering

In [33]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
cbData = newMoviesData.copy()
cbData.head(2)

      budget                        genres  ... runtime_str        director
0  237000000  [Action, Adventure, Fantasy]  ...        2h42   James Cameron
1  300000000  [Adventure, Fantasy, Action]  ...        2h49  Gore Verbinski

[2 rows x 29 columns]

In [0]:
# Function to convert all strings to lower case and strip names of spaces
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''

In [0]:
# Apply clean_data function to your features.
features = ['cast', 'keywords', 'director', 'genres','production_companies']

for feature in features:
    cbData[feature] = cbData[feature].apply(clean_data)

In [36]:
cbData.head(2)

      budget                        genres  ... runtime_str       director
0  237000000  [action, adventure, fantasy]  ...        2h42   jamescameron
1  300000000  [adventure, fantasy, action]  ...        2h49  goreverbinski

[2 rows x 29 columns]

In [37]:
def create_soup(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])#+ ' '.join(x['production_companies'])
  
  
cbData['soup'] = cbData.apply(create_soup, axis=1)

cbData.head(2)

      budget  ...                                               soup
0  237000000  ...  cultureclash future spacewar samworthington zo...
1  300000000  ...  ocean drugabuse exoticisland johnnydepp orland...

[2 rows x 30 columns]

In [0]:
# Import CountVectorizer and create the count matrix
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(cbData['soup'])

In [39]:
count_matrix

<4807x11520 sparse matrix of type '<class 'numpy.int64'>'
	with 42975 stored elements in Compressed Sparse Row format>

In [0]:
# Compute the Cosine Similarity matrix based on the count_matrix
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [0]:
# Function that takes in movie title as input and outputs most similar movies
def get_recommendations(inputData,title, cosine_sim,topN):
  
    data = inputData.copy()
  
    #Construct a reverse map of indices and movie titles
    indices = pd.Series(data.index, index=data['title']).drop_duplicates()

    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:topN]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return data.iloc[movie_indices]#data['title'].iloc[movie_indices]

In [42]:
cbResult = get_recommendations(cbData,'The Dark Knight Rises',cosine_sim2,12)
cbResult[returnColumns]

          id                     title  ... score  popularity
65       155           The Dark Knight  ...   8.2  187.322927
119      272             Batman Begins  ...   7.5  115.040024
4642  378237  Amidst the Devil's Wings  ...   0.0    0.018087
1196    1124              The Prestige  ...   8.0   74.440708
3075    2088         Romeo Is Bleeding  ...   5.7    4.850402
3328  312113            Black November  ...   6.4    1.589693
1503   22907                    Takers  ...   6.0   18.472420
1988   41283                    Faster  ...   6.1   26.324874
303      314                  Catwoman  ...   4.2   32.271938
747    82682            Gangster Squad  ...   6.2   29.041198
1253    6071             Kiss of Death  ...   5.7    6.908940

[11 rows x 5 columns]

In [43]:
oldRatings = pd.read_csv('ratings_small.csv')
userRatings = pd.read_csv('user_rating.csv')
ratings = oldRatings.append(userRatings)
userRatings

    userId  movieId  rating     timestamp
0        1    49026     9.0  1.565061e+09
1        2      120    87.0  1.565067e+09
2        2     7870    86.7  1.565067e+09
3        2     1891    88.9  1.565068e+09
4        2      122    87.0  1.565068e+09
5        2       13    85.5  1.565068e+09
6        2      550    86.7  1.565068e+09
7        2    60308    83.3  1.565068e+09
8        2      680    94.2  1.565068e+09
9        2     1891    84.5  1.565068e+09
10       2      680    85.8  1.565068e+09
11       2       11    87.3  1.565068e+09
12       2     1894    86.7  1.565068e+09
13       2    24746    85.8  1.565068e+09
14       2      680    87.0  1.565068e+09
15       2    79698    76.4  1.565068e+09
16       2      278    88.6  1.565069e+09
17       2     1429    85.5  1.565069e+09
18       2     1891    86.7  1.565069e+09
19       2      120    86.4  1.565069e+09
20       2       13    87.0  1.565069e+09
21       2    44857    81.3  1.565101e+09
22       2    40794    70.0  1.565101e+09
23       2      155    56.3  1.565101e+09
24       2      120    62.2  1.565101e+09
25       2      680    83.1  1.565101e+09
26       2     4551    76.9  1.565101e+09
27       3      120     4.4  1.565131e+09
28       2      285     3.0  1.565135e+09
29       2     5038     3.0  1.565135e+09
30       2   209112     3.0  1.565135e+09
31       2      550     3.0  1.565187e+09
32       2     8077     3.0  1.565187e+09
33       2       75     3.0  1.565187e+09
34       2     8009     3.0  1.565187e+09

In [44]:
oldRatings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100004 entries, 0 to 100003
Data columns (total 4 columns):
userId       100004 non-null int64
movieId      100004 non-null int64
rating       100004 non-null float64
timestamp    100004 non-null int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [45]:
ratings.info()
ratings.tail()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100039 entries, 0 to 34
Data columns (total 4 columns):
userId       100039 non-null int64
movieId      100039 non-null int64
rating       100039 non-null float64
timestamp    100039 non-null float64
dtypes: float64(2), int64(2)
memory usage: 3.8 MB

    userId  movieId  rating     timestamp
30       2   209112     3.0  1.565135e+09
31       2      550     3.0  1.565187e+09
32       2     8077     3.0  1.565187e+09
33       2       75     3.0  1.565187e+09
34       2     8009     3.0  1.565187e+09

In [0]:
def getLatestMovieByUserId(ratingData,moviesData,userId):
  df = ratingData.copy()
  df = ratingData[ratingData['userId']==userId]
  df = df.sort_values('timestamp', ascending=False)
  df.columns=['userId','id','rating','timestamp']
  data = pd.merge(df,moviesData, how='left', on=['id'])
  print(data[['id','original_title']])
  data = data.dropna(subset=['original_title'])
  print(data[['id','original_title']])
  
  
  title = data.head(1)

  return title['original_title'].item()

In [47]:
getLatestMovieByUserId(ratings,newMoviesData,2)

         id                                     original_title
0      8009                                         Highlander
1        75                                      Mars Attacks!
2      8077                                             Alien³
3       550                                         Fight Club
4    209112                 Batman v Superman: Dawn of Justice
5      5038                           Vicky Cristina Barcelona
6       285           Pirates of the Caribbean: At World's End
7      4551                                            Be Cool
8       680                                       Pulp Fiction
9       120  The Lord of the Rings: The Fellowship of the Ring
10      155                                    The Dark Knight
11    40794                                       Mine vaganti
12    44857                                              Molly
13       13                                       Forrest Gump
14      120  The Lord of the Rings: The Fellowship of the Ring
15     1891                            The Empire Strikes Back
16     1429                                          25th Hour
17      278                           The Shawshank Redemption
18    79698                                         The Lovers
19      680                                       Pulp Fiction
20    24746                                 Six-String Samurai
21     1894       Star Wars: Episode II - Attack of the Clones
22       11                                          Star Wars
23      680                                       Pulp Fiction
24     1891                            The Empire Strikes Back
25      680                                       Pulp Fiction
26    60308                                          Moneyball
27      550                                         Fight Club
28       13                                       Forrest Gump
29      122      The Lord of the Rings: The Return of the King
..      ...                                                ...
79      356                                                NaN
80      367                                                NaN
81      454                                     Romeo + Juliet
82      364                                     Batman Returns
83       39                                                NaN
84       50                                                NaN
85      266                                                NaN
86       47                                                NaN
87      225                                                NaN
88      317                                                NaN
89      300                                                NaN
90      410                                                NaN
91      110                                                NaN
92      253                                   Live and Let Die
93      593                                            Солярис
94      208                                                NaN
95      457                                                NaN
96      185                                                NaN
97      161                                     Ocean's Eleven
98       10                                                NaN
99      292                       Dave Chappelle's Block Party
100     339                                                NaN
101     165                         Back to the Future Part II
102     153                                Lost in Translation
103     588                                        Silent Hill
104     349                                                NaN
105     150                                                NaN
106     296                 Terminator 3: Rise of the Machines
107     592                                   The Conversation
108     590                                          The Hours

[109 rows x 2 columns]
         id                                     original_title
0      8009                                         Highlander
1        75                                      Mars Attacks!
2      8077                                             Alien³
3       550                                         Fight Club
4    209112                 Batman v Superman: Dawn of Justice
5      5038                           Vicky Cristina Barcelona
6       285           Pirates of the Caribbean: At World's End
7      4551                                            Be Cool
8       680                                       Pulp Fiction
9       120  The Lord of the Rings: The Fellowship of the Ring
10      155                                    The Dark Knight
11    40794                                       Mine vaganti
12    44857                                              Molly
13       13                                       Forrest Gump
14      120  The Lord of the Rings: The Fellowship of the Ring
15     1891                            The Empire Strikes Back
16     1429                                          25th Hour
17      278                           The Shawshank Redemption
18    79698                                         The Lovers
19      680                                       Pulp Fiction
20    24746                                 Six-String Samurai
21     1894       Star Wars: Episode II - Attack of the Clones
22       11                                          Star Wars
23      680                                       Pulp Fiction
24     1891                            The Empire Strikes Back
25      680                                       Pulp Fiction
26    60308                                          Moneyball
27      550                                         Fight Club
28       13                                       Forrest Gump
29      122      The Lord of the Rings: The Return of the King
..      ...                                                ...
50      508                                      Love Actually
55      585                                     Monsters, Inc.
56      468                               My Own Private Idaho
57      586                                        Wag the Dog
59      587                                           Big Fish
60      272                                      Batman Begins
61      539                                             Psycho
64      223                                            Rebecca
65       62                              2001: A Space Odyssey
66      500                                     Reservoir Dogs
68      509                                       Notting Hill
69      377                          A Nightmare on Elm Street
70      168                      Star Trek IV: The Voyage Home
73      350                              The Devil Wears Prada
74      261                              Cat on a Hot Tin Roof
76      186                                Lucky Number Slevin
77      235                                        Stand by Me
78      480                                    Monsoon Wedding
81      454                                     Romeo + Juliet
82      364                                     Batman Returns
92      253                                   Live and Let Die
93      593                                            Солярис
97      161                                     Ocean's Eleven
99      292                       Dave Chappelle's Block Party
101     165                         Back to the Future Part II
102     153                                Lost in Translation
103     588                                        Silent Hill
106     296                 Terminator 3: Rise of the Machines
107     592                                   The Conversation
108     590                                          The Hours

[69 rows x 2 columns]

'Highlander'

# Get Video Info

In [48]:
def getFilmInfo(data,id):
  return data[data['id'] == id]

getFilmInfo(newMoviesData,6071)

        budget                  genres  ... runtime_str          director
1253  40000000  [Action, Crime, Drama]  ...        1h41  Barbet Schroeder

[1 rows x 29 columns]

In [49]:
userId=1
movieId = 49026	

uRating = ratings[ratings['userId']== userId]

uRating = uRating[uRating['movieId']== movieId]
uRating
if(uRating['rating'].count()>0):
  r = uRating['rating'].item()
else:
  r = 0
r

9.0

In [0]:
def getRatingByUser(userId,movieId):

    print(ratings)
    print(userId)

    print(movieId)

    uRating = ratings[ratings['userId'] == userId]

    print(uRating)

    uRating = uRating[uRating['movieId'] == movieId]


    print(uRating)


    if (uRating['rating'].count() > 0):
        r = uRating['rating'].item()
    else:
        r = 0

    print(r)
    return r

In [51]:
getRatingByUser(1,49026)

    userId  movieId  rating     timestamp
0        1       31     2.5  1.260759e+09
1        1     1029     3.0  1.260759e+09
2        1     1061     3.0  1.260759e+09
3        1     1129     2.0  1.260759e+09
4        1     1172     4.0  1.260759e+09
5        1     1263     2.0  1.260759e+09
6        1     1287     2.0  1.260759e+09
7        1     1293     2.0  1.260759e+09
8        1     1339     3.5  1.260759e+09
9        1     1343     2.0  1.260759e+09
10       1     1371     2.5  1.260759e+09
11       1     1405     1.0  1.260759e+09
12       1     1953     4.0  1.260759e+09
13       1     2105     4.0  1.260759e+09
14       1     2150     3.0  1.260759e+09
15       1     2193     2.0  1.260759e+09
16       1     2294     2.0  1.260759e+09
17       1     2455     2.5  1.260759e+09
18       1     2968     1.0  1.260759e+09
19       1     3671     3.0  1.260759e+09
20       2       10     4.0  8.353555e+08
21       2       17     5.0  8.353557e+08
22       2       39     5.0  8.353556e+08
23       2       47     4.0  8.353556e+08
24       2       50     4.0  8.353556e+08
25       2       52     3.0  8.353560e+08
26       2       62     3.0  8.353557e+08
27       2      110     4.0  8.353555e+08
28       2      144     3.0  8.353560e+08
29       2      150     5.0  8.353554e+08
..     ...      ...     ...           ...
5        2       13    85.5  1.565068e+09
6        2      550    86.7  1.565068e+09
7        2    60308    83.3  1.565068e+09
8        2      680    94.2  1.565068e+09
9        2     1891    84.5  1.565068e+09
10       2      680    85.8  1.565068e+09
11       2       11    87.3  1.565068e+09
12       2     1894    86.7  1.565068e+09
13       2    24746    85.8  1.565068e+09
14       2      680    87.0  1.565068e+09
15       2    79698    76.4  1.565068e+09
16       2      278    88.6  1.565069e+09
17       2     1429    85.5  1.565069e+09
18       2     1891    86.7  1.565069e+09
19       2      120    86.4  1.565069e+09
20       2       13    87.0  1.565069e+09
21       2    44857    81.3  1.565101e+09
22       2    40794    70.0  1.565101e+09
23       2      155    56.3  1.565101e+09
24       2      120    62.2  1.565101e+09
25       2      680    83.1  1.565101e+09
26       2     4551    76.9  1.565101e+09
27       3      120     4.4  1.565131e+09
28       2      285     3.0  1.565135e+09
29       2     5038     3.0  1.565135e+09
30       2   209112     3.0  1.565135e+09
31       2      550     3.0  1.565187e+09
32       2     8077     3.0  1.565187e+09
33       2       75     3.0  1.565187e+09
34       2     8009     3.0  1.565187e+09

[100039 rows x 4 columns]
1
49026
    userId  movieId  rating     timestamp
0        1       31     2.5  1.260759e+09
1        1     1029     3.0  1.260759e+09
2        1     1061     3.0  1.260759e+09
3        1     1129     2.0  1.260759e+09
4        1     1172     4.0  1.260759e+09
5        1     1263     2.0  1.260759e+09
6        1     1287     2.0  1.260759e+09
7        1     1293     2.0  1.260759e+09
8        1     1339     3.5  1.260759e+09
9        1     1343     2.0  1.260759e+09
10       1     1371     2.5  1.260759e+09
11       1     1405     1.0  1.260759e+09
12       1     1953     4.0  1.260759e+09
13       1     2105     4.0  1.260759e+09
14       1     2150     3.0  1.260759e+09
15       1     2193     2.0  1.260759e+09
16       1     2294     2.0  1.260759e+09
17       1     2455     2.5  1.260759e+09
18       1     2968     1.0  1.260759e+09
19       1     3671     3.0  1.260759e+09
0        1    49026     9.0  1.565061e+09
   userId  movieId  rating     timestamp
0       1    49026     9.0  1.565061e+09
9.0

9.0

In [52]:
userId
movieId = 1029

uRating = ratings[ratings['userId']== userId]
uRating

    userId  movieId  rating     timestamp
0        1       31     2.5  1.260759e+09
1        1     1029     3.0  1.260759e+09
2        1     1061     3.0  1.260759e+09
3        1     1129     2.0  1.260759e+09
4        1     1172     4.0  1.260759e+09
5        1     1263     2.0  1.260759e+09
6        1     1287     2.0  1.260759e+09
7        1     1293     2.0  1.260759e+09
8        1     1339     3.5  1.260759e+09
9        1     1343     2.0  1.260759e+09
10       1     1371     2.5  1.260759e+09
11       1     1405     1.0  1.260759e+09
12       1     1953     4.0  1.260759e+09
13       1     2105     4.0  1.260759e+09
14       1     2150     3.0  1.260759e+09
15       1     2193     2.0  1.260759e+09
16       1     2294     2.0  1.260759e+09
17       1     2455     2.5  1.260759e+09
18       1     2968     1.0  1.260759e+09
19       1     3671     3.0  1.260759e+09
0        1    49026     9.0  1.565061e+09

# Collaboration Filtering

In [0]:
def convert_int(x):
    try:
        return int(x)
    except:
        return np.nan

In [54]:
pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.6/dist-packages (1.0.6)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-surprise) (1.3.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from scikit-surprise) (1.12.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-surprise) (0.13.2)
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python3.6/dist-packages (from scikit-surprise) (1.16.4)

In [55]:
from surprise import Reader, Dataset, SVD, evaluate
reader = Reader()
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)
data.split(n_folds=5)
svd = SVD()
evaluate(svd, data, measures=['RMSE', 'MAE'])

/usr/local/lib/python3.6/dist-packages/surprise/evaluate.py:66: UserWarning: The evaluate() method is deprecated. Please use model_selection.cross_validate() instead.
  'model_selection.cross_validate() instead.', UserWarning)
/usr/local/lib/python3.6/dist-packages/surprise/dataset.py:193: UserWarning: Using data.split() or using load_from_folds() without using a CV iterator is now deprecated.
  UserWarning)

Evaluating RMSE, MAE of algorithm SVD.

------------
Fold 1
RMSE: 1.5743
MAE:  0.7120
------------
Fold 2
RMSE: 1.6348
MAE:  0.7136
------------
Fold 3
RMSE: 1.2292
MAE:  0.6980
------------
Fold 4
RMSE: 1.4522
MAE:  0.7074
------------
Fold 5
RMSE: 1.8087
MAE:  0.7294
------------
------------
Mean RMSE: 1.5398
Mean MAE : 0.7121
------------
------------

CaseInsensitiveDefaultDict(list,
                           {'mae': [0.7119844105042916,
                             0.7135630098796878,
                             0.6979789012658771,
                             0.7073589848799375,
                             0.7294089724513924],
                            'rmse': [1.574308313528461,
                             1.6348406186541,
                             1.2291716100730807,
                             1.452151319582425,
                             1.808746779136242]})

In [56]:
trainset = data.build_full_trainset()
svd.train(trainset)

/usr/local/lib/python3.6/dist-packages/surprise/prediction_algorithms/algo_base.py:51: UserWarning: train() is deprecated. Use fit() instead
  warnings.warn('train() is deprecated. Use fit() instead', UserWarning)

In [57]:
svd.predict(1, 302)

Prediction(uid=1, iid=302, r_ui=None, est=2.8024703154839687, details={'was_impossible': False})

In [58]:
svd.predict(1, 4444444444, 5555)

Prediction(uid=1, iid=4444444444, r_ui=5555, est=2.913903668821179, details={'was_impossible': False})

In [59]:
userId= 1
svd.predict(userId, 4444444444)

Prediction(uid=1, iid=4444444444, r_ui=None, est=2.913903668821179, details={'was_impossible': False})

In [60]:
ratingData = ratings[ratings['userId']!=userId]
movieId = ratingData['movieId']
movieIndice = movieId.unique()
movieIndice

array([    10,     17,     39, ..., 209112,   8077,     75])

In [61]:
moviesCF = newMoviesData.loc[newMoviesData['id'].isin(movieIndice)]
moviesCF.head(3)

      budget                        genres  ... runtime_str        director
1  300000000  [Adventure, Fantasy, Action]  ...        2h49  Gore Verbinski
5  258000000  [Fantasy, Action, Adventure]  ...        2h19       Sam Raimi
8  250000000  [Adventure, Fantasy, Family]  ...        2h33     David Yates

[3 rows x 29 columns]

In [62]:
moviesCF['est']=moviesCF['id'].apply(lambda x: svd.predict(userId, x).est)
moviesCF = moviesCF.sort_values('est', ascending=False)
moviesCF.head(2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

        budget                                genres  ...           director  est
1992  18000000  [Adventure, Action, Science Fiction]  ...     Irvin Kershner  5.0
3234   8000000                     [Thriller, Crime]  ...  Quentin Tarantino  5.0

[2 rows x 30 columns]

In [63]:
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)
data.split(n_folds=5)
svd = SVD()
evaluate(svd, data, measures=['RMSE', 'MAE'])
trainset = data.build_full_trainset()
svd.train(trainset)

/usr/local/lib/python3.6/dist-packages/surprise/evaluate.py:66: UserWarning: The evaluate() method is deprecated. Please use model_selection.cross_validate() instead.
  'model_selection.cross_validate() instead.', UserWarning)
/usr/local/lib/python3.6/dist-packages/surprise/dataset.py:193: UserWarning: Using data.split() or using load_from_folds() without using a CV iterator is now deprecated.
  UserWarning)

Evaluating RMSE, MAE of algorithm SVD.

------------
Fold 1
RMSE: 1.4105
MAE:  0.7124
------------
Fold 2
RMSE: 1.4099
MAE:  0.7084
------------
Fold 3
RMSE: 1.6523
MAE:  0.7097
------------
Fold 4
RMSE: 1.6459
MAE:  0.7150
------------
Fold 5
RMSE: 1.6194
MAE:  0.7127
------------
------------
Mean RMSE: 1.5476
Mean MAE : 0.7116
------------
------------

/usr/local/lib/python3.6/dist-packages/surprise/prediction_algorithms/algo_base.py:51: UserWarning: train() is deprecated. Use fit() instead
  warnings.warn('train() is deprecated. Use fit() instead', UserWarning)

In [0]:
def convert_int(x):
    try:
        return int(x)
    except:
        return np.nan

from surprise import Reader, Dataset, SVD, evaluate
reader = Reader()





def collaborationFiltering(ratings,newMoviesData,userId):
  
  
  ratingData = ratings[ratings['userId']!=userId]
  movieId = ratingData['movieId']
  movieIndice = movieId.unique()
  movieIndice

  moviesCF = newMoviesData.loc[newMoviesData['id'].isin(movieIndice)]
  #moviesCF.head(3)

  moviesCF['est']=moviesCF['id'].apply(lambda x: svd.predict(userId, x).est)
  moviesCF = moviesCF.sort_values('est', ascending=False)
  #moviesCF.head(2)
  
  return moviesCF

In [65]:
collaborationFiltering(ratings,newMoviesData,1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

         budget  ...       est
1992   18000000  ...  4.014246
93    200000000  ...  3.899574
4461          0  ...  3.892978
262    93000000  ...  3.874300
1666          0  ...  3.837999
1145   40000000  ...  3.814099
425    80000000  ...  3.788165
4285    1288000  ...  3.778022
150   140000000  ...  3.762900
1749   15000000  ...  3.734993
1028          0  ...  3.706148
2218   20000000  ...  3.665663
3340    4000000  ...  3.655186
1053   45000000  ...  3.653107
1170   40000000  ...  3.645134
1391   35000000  ...  3.638959
3234    8000000  ...  3.617521
1603   30000000  ...  3.613562
388    85000000  ...  3.590848
2532   15000000  ...  3.568821
1783   15000000  ...  3.566456
1025   48000000  ...  3.563496
882           0  ...  3.552020
386    75000000  ...  3.531668
690    60000000  ...  3.526926
878    90000000  ...  3.525792
1260   10000000  ...  3.524648
2855   12000000  ...  3.523707
2801   12800000  ...  3.512684
2280   22000000  ...  3.511143
...         ...  ...       ...
3851    3500000  ...  2.214647
3522    3500159  ...  2.212175
2127   20000000  ...  2.191978
3741    4000000  ...  2.162636
2977   10000000  ...  2.152410
3431          0  ...  2.151808
332   115000000  ...  2.148467
940    50000000  ...  2.145710
4006    2600000  ...  2.123737
1203   40000000  ...  2.115491
4583     400000  ...  2.087798
1165   40000000  ...  2.086942
2890   12000000  ...  2.076511
1438   27000000  ...  2.047042
3259    7000000  ...  2.037687
114   150000000  ...  2.029284
191   130000000  ...  2.029015
106   160000000  ...  2.025133
1583   30000000  ...  2.022951
1303   38000000  ...  1.982268
3570    5000000  ...  1.956328
212   125000000  ...  1.920211
2640   92620000  ...  1.919072
2071   21000000  ...  1.844843
2563   15000000  ...  1.796810
703    60000000  ...  1.793713
1906   25000000  ...  1.777709
1141   41000000  ...  1.740584
1021   48000000  ...  1.659594
4350    1000000  ...  1.469085

[869 rows x 30 columns]

In [66]:
newMoviesData.head(2)

      budget                        genres  ... runtime_str        director
0  237000000  [Action, Adventure, Fantasy]  ...        2h42   James Cameron
1  300000000  [Adventure, Fantasy, Action]  ...        2h49  Gore Verbinski

[2 rows x 29 columns]

In [67]:
newMoviesData[newMoviesData['title'].str.contains('ava',case=False,na=False, regex=False)]

         budget  ...          director
0     237000000  ...     James Cameron
960    50000000  ...  Robert Rodriguez
1075   45000000  ...      Oliver Stone
2710          0  ...       James Fargo
3180          0  ...    Tamara Jenkins
3621    5000000  ...      Guy Hamilton
3695    4600000  ...         Tom Kalin

[7 rows x 29 columns]

# NCF

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline
#https://nipunbatra.github.io/blog/2017/neural-collaborative-filtering.html
oldRatings = pd.read_csv('ratings_small.csv')
userRatings = pd.read_csv('user_rating.csv')
ratings = oldRatings.append(userRatings)
userRatings
dataset = ratings.copy()
dataset.columns=['user_id','item_id','rating','timestamp']
dataset.user_id = dataset.user_id.astype('category').cat.codes.values
dataset.item_id = dataset.item_id.astype('category').cat.codes.values

In [69]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(dataset, test_size=0.2)
train.head()

       user_id  item_id  rating     timestamp
27816      201     1080     4.0  1.046146e+09
80405      546     7040     3.0  1.270485e+09
13417       85      450     5.0  8.481603e+08
15316      100      968     4.5  1.292403e+09
36021      261      523     2.0  1.433901e+09

In [0]:
test.head()
y_true = test.rating

Creating the model

In [71]:
import keras
n_latent_factors_user = 8
n_latent_factors_movie = 10
n_latent_factors_mf = 3
n_users, n_movies = len(dataset.user_id.unique()), len(dataset.item_id.unique())

movie_input = keras.layers.Input(shape=[1],name='Item')
movie_embedding_mlp = keras.layers.Embedding(n_movies + 1, n_latent_factors_movie, name='Movie-Embedding-MLP')(movie_input)
movie_vec_mlp = keras.layers.Flatten(name='FlattenMovies-MLP')(movie_embedding_mlp)
movie_vec_mlp = keras.layers.Dropout(0.2)(movie_vec_mlp)

movie_embedding_mf = keras.layers.Embedding(n_movies + 1, n_latent_factors_mf, name='Movie-Embedding-MF')(movie_input)
movie_vec_mf = keras.layers.Flatten(name='FlattenMovies-MF')(movie_embedding_mf)
movie_vec_mf = keras.layers.Dropout(0.2)(movie_vec_mf)


user_input = keras.layers.Input(shape=[1],name='User')
user_vec_mlp = keras.layers.Flatten(name='FlattenUsers-MLP')(keras.layers.Embedding(n_users + 1, n_latent_factors_user,name='User-Embedding-MLP')(user_input))
user_vec_mlp = keras.layers.Dropout(0.2)(user_vec_mlp)

user_vec_mf = keras.layers.Flatten(name='FlattenUsers-MF')(keras.layers.Embedding(n_users + 1, n_latent_factors_mf,name='User-Embedding-MF')(user_input))
user_vec_mf = keras.layers.Dropout(0.2)(user_vec_mf)

concat = keras.layers.merge.Concatenate()([movie_vec_mlp, user_vec_mlp])
#concat = keras.layers.merge([movie_vec_mlp, user_vec_mlp], mode='concat',name='Concat')
concat_dropout = keras.layers.Dropout(0.2)(concat)
dense = keras.layers.Dense(200,name='FullyConnected')(concat_dropout)
dense_batch = keras.layers.BatchNormalization(name='Batch')(dense)
dropout_1 = keras.layers.Dropout(0.2,name='Dropout-1')(dense_batch)
dense_2 = keras.layers.Dense(100,name='FullyConnected-1')(dropout_1)
dense_batch_2 = keras.layers.BatchNormalization(name='Batch-2')(dense_2)


dropout_2 = keras.layers.Dropout(0.2,name='Dropout-2')(dense_batch_2)
dense_3 = keras.layers.Dense(50,name='FullyConnected-2')(dropout_2)
dense_4 = keras.layers.Dense(20,name='FullyConnected-3', activation='relu')(dense_3)
from keras.layers import dot

#pred_mf = keras.layers.merge([movie_vec_mf, user_vec_mf], mode='dot',name='Dot')
pred_mf = dot([movie_vec_mf, user_vec_mf], axes=1, normalize=False)


pred_mlp = keras.layers.Dense(1, activation='relu',name='Activation')(dense_4)

#combine_mlp_mf = keras.layers.merge([pred_mf, pred_mlp], mode='concat',name='Concat-MF-MLP')
combine_mlp_mf = keras.layers.merge.Concatenate()([pred_mf, pred_mlp])


result_combine = keras.layers.Dense(100,name='Combine-MF-MLP')(combine_mlp_mf)
deep_combine = keras.layers.Dense(100,name='FullyConnected-4')(result_combine)


result = keras.layers.Dense(1,name='Prediction')(deep_combine)


model = keras.Model([user_input, movie_input], result)
opt = keras.optimizers.Adam(lr =0.01)
model.compile(optimizer='adam',loss= 'mean_absolute_error')

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0807 20:15:45.346560 139825938798464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0807 20:15:45.364559 139825938798464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0807 20:15:45.388923 139825938798464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0807 20:15:45.390219 139825938798464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0807 20:15:45.402858 139825938798464 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0807 20:15:46.065374 139825938798464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [72]:
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
SVG(model_to_dot(model,  show_shapes=False, show_layer_names=True, rankdir='HB').create(prog='dot', format='svg'))

In [73]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
Item (InputLayer)               (None, 1)            0
__________________________________________________________________________________________________
User (InputLayer)               (None, 1)            0
__________________________________________________________________________________________________
Movie-Embedding-MLP (Embedding) (None, 1, 10)        90790       Item[0][0]
__________________________________________________________________________________________________
User-Embedding-MLP (Embedding)  (None, 1, 8)         5376        User[0][0]
__________________________________________________________________________________________________
FlattenMovies-MLP (Flatten)     (None, 10)           0           Movie-Embedding-MLP[0][0]
__________________________________________________________________________________________________
FlattenUsers-MLP (Flatten)      (None, 8)            0           User-Embedding-MLP[0][0]
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 10)           0           FlattenMovies-MLP[0][0]
__________________________________________________________________________________________________
dropout_3 (Dropout)             (None, 8)            0           FlattenUsers-MLP[0][0]
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 18)           0           dropout_1[0][0]
                                                                 dropout_3[0][0]
__________________________________________________________________________________________________
dropout_5 (Dropout)             (None, 18)           0           concatenate_1[0][0]
__________________________________________________________________________________________________
FullyConnected (Dense)          (None, 200)          3800        dropout_5[0][0]
__________________________________________________________________________________________________
Batch (BatchNormalization)      (None, 200)          800         FullyConnected[0][0]
__________________________________________________________________________________________________
Dropout-1 (Dropout)             (None, 200)          0           Batch[0][0]
__________________________________________________________________________________________________
FullyConnected-1 (Dense)        (None, 100)          20100       Dropout-1[0][0]
__________________________________________________________________________________________________
Batch-2 (BatchNormalization)    (None, 100)          400         FullyConnected-1[0][0]
__________________________________________________________________________________________________
Movie-Embedding-MF (Embedding)  (None, 1, 3)         27237       Item[0][0]
__________________________________________________________________________________________________
User-Embedding-MF (Embedding)   (None, 1, 3)         2016        User[0][0]
__________________________________________________________________________________________________
Dropout-2 (Dropout)             (None, 100)          0           Batch-2[0][0]
__________________________________________________________________________________________________
FlattenMovies-MF (Flatten)      (None, 3)            0           Movie-Embedding-MF[0][0]
__________________________________________________________________________________________________
FlattenUsers-MF (Flatten)       (None, 3)            0           User-Embedding-MF[0][0]
__________________________________________________________________________________________________
FullyConnected-2 (Dense)        (None, 50)           5050        Dropout-2[0][0]
__________________________________________________________________________________________________
dropout_2 (Dropout)             (None, 3)            0           FlattenMovies-MF[0][0]
__________________________________________________________________________________________________
dropout_4 (Dropout)             (None, 3)            0           FlattenUsers-MF[0][0]
__________________________________________________________________________________________________
FullyConnected-3 (Dense)        (None, 20)           1020        FullyConnected-2[0][0]
__________________________________________________________________________________________________
dot_1 (Dot)                     (None, 1)            0           dropout_2[0][0]
                                                                 dropout_4[0][0]
__________________________________________________________________________________________________
Activation (Dense)              (None, 1)            21          FullyConnected-3[0][0]
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, 2)            0           dot_1[0][0]
                                                                 Activation[0][0]
__________________________________________________________________________________________________
Combine-MF-MLP (Dense)          (None, 100)          300         concatenate_2[0][0]
__________________________________________________________________________________________________
FullyConnected-4 (Dense)        (None, 100)          10100       Combine-MF-MLP[0][0]
__________________________________________________________________________________________________
Prediction (Dense)              (None, 1)            101         FullyConnected-4[0][0]
==================================================================================================
Total params: 167,111
Trainable params: 166,511
Non-trainable params: 600
__________________________________________________________________________________________________

In [74]:
history = model.fit([train.user_id, train.item_id], train.rating, epochs=25, verbose=0, validation_split=0.1)

W0807 20:15:46.986124 139825938798464 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

In [75]:
from sklearn.metrics import mean_absolute_error
y_hat_2 = np.round(model.predict([test.user_id, test.item_id]),0)
print(mean_absolute_error(y_true, y_hat_2))

print(mean_absolute_error(y_true, model.predict([test.user_id, test.item_id])))

0.7013694522191124
0.7106990395229263

In [76]:
print(model.predict([test.user_id, test.item_id]))

[[3.209126 ]
 [3.5674531]
 [3.3033366]
 ...
 [4.0046363]
 [3.8998377]
 [3.6338599]]

In [0]:
userId=1

In [78]:
ratingData = ratings[ratings['userId'] != userId]
uRatingData = ratings[ratings['userId'] == userId]
uMovieId = uRatingData['movieId']

movieId = ratingData['movieId']

movieId = movieId.loc[~movieId.isin(uMovieId)]


movieIndice = movieId.unique()

print(movieIndice)

moviesCF = newMoviesData.loc[newMoviesData['id'].isin(movieIndice)]
moviesCF.head(3)

[    10     17     39 ... 209112   8077     75]

      budget                        genres  ... runtime_str        director
1  300000000  [Adventure, Fantasy, Action]  ...        2h49  Gore Verbinski
5  258000000  [Fantasy, Action, Adventure]  ...        2h19       Sam Raimi
8  250000000  [Adventure, Fantasy, Family]  ...        2h33     David Yates

[3 rows x 29 columns]

In [0]:
#moviesCF['id'].apply(lambda x: x)

In [0]:
#9072
moviesCF = moviesCF[moviesCF['id']<9072]
moviesCF['userId'] = userId
moviesCF
moviesCF['est'] = model.predict([moviesCF['userId'], moviesCF['id']])
moviesCF = moviesCF.sort_values('est', ascending=False)

In [80]:
returnColumns = ['id', 'title', 'imgURL','popularity', 'est']
CFResult = moviesCF[returnColumns].head(nRows)
CFResult

        id                   title  ... popularity        est
4085   582     The Lives of Others  ...  34.938177  27.278826
328     12            Finding Nemo  ...  85.688789  12.869663
292   2486                  Eragon  ...  30.863434  12.833629
1831  6977  No Country for Old Men  ...  53.645267  12.674346
2188  7979         The Kite Runner  ...  10.446722  12.638710
2824   184            Jackie Brown  ...  40.631671  11.926444
929   6950                Outbreak  ...  30.397496  11.301071
527   4551                 Be Cool  ...  18.614720  11.157706
2127  1975            The Grudge 2  ...  13.906944  10.869271
3242   170           28 Days Later  ...  45.490374  10.564714
1082  2207               16 Blocks  ...  32.310220  10.051045

[11 rows x 5 columns]

# References

https://arxiv.org/pdf/1707.07435.pdf

https://www.kaggle.com/ibtesama/getting-started-with-a-movie-recommendation-system#Collaborative-Filtering

https://nipunbatra.github.io/blog/2017/neural-collaborative-filtering.html